name: Build-Publish-Docker-Images
on: [push]

jobs:
  build_client_api:
    name: Publish Client API Docker Image
    # if:  github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:

    - name: checkout-repo
      uses: actions/checkout@v4
      with:
        clean: 'true'

    - name: docker-login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: docker-build-push-clientapi
      uses: docker/build-push-action@v5
      with:
        push: true
        context: ./src
        file: ./build/client.dockerfile
        tags: | 
          ghcr.io/${{ github.repository }}/azisddaprclient:${{github.run_number}}
          ghcr.io/${{ github.repository }}/azisddaprclient:latest

  build_server_api:
    name: Publish Server API Docker Image
    # if:  github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:

    - name: checkout-repo
      uses: actions/checkout@v4
      with:
        clean: 'true'

    - name: docker-login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: docker-build-push-clientapi
      uses: docker/build-push-action@v5
      with:
        push: true
        context: ./src
        file: ./build/server.dockerfile
        tags: | 
          ghcr.io/${{ github.repository }}/azisddaprserver:${{github.run_number}}
          ghcr.io/${{ github.repository }}/azisddaprserver:latest